/**
 * Domain enums shared by web and api. Keep in sync with docs/DATA_MODEL.md §2.
 */

export enum Role {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum DoctorStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  RESCHEDULED = 'RESCHEDULED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  NO_SHOW = 'NO_SHOW',
}

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  JOINED = 'JOINED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum CancelledBy {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

export enum NotificationType {
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  SCHEDULE_CHANGED = 'SCHEDULE_CHANGED',
  CONSULTATION_READY = 'CONSULTATION_READY',
  NOTE_AVAILABLE = 'NOTE_AVAILABLE',
  PRESCRIPTION_ISSUED = 'PRESCRIPTION_ISSUED',
  DOCTOR_PROFILE_REVIEWED = 'DOCTOR_PROFILE_REVIEWED',
  ACCOUNT_STATUS_CHANGED = 'ACCOUNT_STATUS_CHANGED',
}

export enum AuditAction {
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_DEACTIVATED = 'USER_DEACTIVATED',
  DOCTOR_APPROVED = 'DOCTOR_APPROVED',
  DOCTOR_REJECTED = 'DOCTOR_REJECTED',
  DOCTOR_PROFILE_UPDATED = 'DOCTOR_PROFILE_UPDATED',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESOLVED = 'APPOINTMENT_RESOLVED',
}
